# Generated by Django 5.1.2 on 2024-11-11 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recepie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recepie_name', models.CharField(max_length=100)),
                ('recepie_desc', models.TextField()),
                ('recepie_imp', models.ImageField(upload_to='recepie')),
            ],
        ),
    ]
